### ISSUE TITLE
Laísmo (pág. 14, último párrafo)

### ISSUE THREAD

**Issue by davibern** [midudev/libro-aprendiendo-git-issues#1]
Hola Midu, 

Te dejo esta sugerencia, la cual y salvo error por mi parte, se trataría de un laísmo.

Se encuentra, en:

- Capítulo: un poco de teoría.
- Sección: los tres estados de git.
- Ubicación: después de la imagen del viaje de los ficheros, segundo párrafo.

![image](https://user-images.githubusercontent.com/13550820/132260292-842bdf26-b79f-48a4-a812-6967c65f6913.png)

Actualmente:
> [...] entonces lo moveríamos al estado de preparado y, de ahí, **lo** grabaríamos el repositorio y lo dejaríamos como confirmado.

Propuesta:
> [...] entonces lo moveríamos al estado de preparado y, de ahí, grabaríamos el repositorio y lo dejaríamos como confirmado.

Ya me confirmas si te trataría efectivamente de un laísmo, y si no es así, disculpa las molestias.

**Comment by midudev** [comment]
¿Es posible que lo correcto fuese "y, de ahí, lo grabaríamos **en** el repositorio". El "lo" es por "el fichero". ¿Cómo lo ves?

**Comment by davibern** [comment]
Veo que ya la has cerrado :)

Sólo comentarte que me parece bien 👍
