### ISSUE TITLE
git checkout "restaurar todo el directorio" (pag 35)

### ISSUE THREAD

**Issue by KevinCamos** [midudev/libro-aprendiendo-git-issues#11]
Buenas noches Midudev!!!

En la página 34 en el comando "restore" nos muestras como restaurar un archivo, un  directorio de trabajo y tipos de archivos por extensiones. Luego en la página 35 muestras como hacer lo mismo con el comando "checkout" pero solamente con el ejemplo de restaurar un archivo y tipos de archivos por extensiones. 

En el caso de poderse hacer, creo que por coherencia se agradecería que estuviese también la restauración de archivos por directorio, y si no se puede, una nota o aclaración.

**Comment by midudev** [comment]
Arreglado!
