### ISSUE TITLE
Frase incompleta en "Clonando un repositorio remoto ya creado previamente"

### ISSUE THREAD

**Issue by pasagedev** [midudev/libro-aprendiendo-git-issues#12]
Creo que la frase inicial del texto seleccionado en la imagen está inconclusa.

![Screenshot_20210909-152329](https://user-images.githubusercontent.com/77918449/132694639-8c2ea143-b48e-4543-8a10-9f8baafab2d4.png)

**Comment by midudev** [comment]
En la próxima versión estará solucionado ya que se escribe la sección completa (estaba a medias y se me coló).
