### ISSUE TITLE
Asistente de instalación de Windows

### ISSUE THREAD

**Issue by montyclt** [midudev/libro-aprendiendo-git-issues#13]
Página 21, al final de la misma se puede leer:

> En Windows es más sencillo descargar el instalador oficial y seguir los pasos:
https://git-scm.com/download/win.

Recomiendo cambiarlo por:
> En Windows es más sencillo descargar el instalador oficial y seguir los pasos del asistente:
https://git-scm.com/download/win.

**Motivación:**
Creo que no indicar que los pasos a seguir son los del asistente de instalación, puede inducir a confusión de que se trata de seguir pasos en la web oficial de Git.

**Los pasos del asistente:**
El asistente de instalación en Windows te pregunta algunas cosas a configurar (formato de fin de línea al hacer pull o push, herramientas por defecto, etc.). Creo que puede ser interesante explicar que es cada una de las preguntas que el asistente te hace. Ahora mismo no tengo un PC a mano, pero en los próximos días podría escribir que son cada una de las opciones del asistente, cuál elegir y por qué.

**Comment by Cloweling** [comment]
@montyclt buena, deberia tambien tener una nota recomendar tener seleccionado la instalacion de ssh.

**Comment by midudev** [comment]
Hey @montyclt. Lo cierto es que no tengo un sistema Windows para revisar los pasos. Si me añades los pasos por aquí e incluso alguna foto, estaría genial. Por ahora voy a arreglar lo que comentas en la issue y ya gestionamos el resto en otra. ¡Gracias!

**Comment by montyclt** [comment]
Hola @midudev, lo cierto es que yo ahora mismo tampoco tengo un PC a mano con Windows porque desde hace tiempo trabajo con macOS y hace varios años que lo instalé en Windows, ahora mismo sólo recuerdo que entre las opciones era el formato de fin de línea al hacer pull/push, e instalar un emulador de bash con herramientas de GNU.

De todas formas, no te preocupes, que a lo largo de la semana pillaré un hueco y un ordenador y haré capturas de todo el asistente de configuración, así como explicar que es todo.

¿Creo una nueva issue cuando lo tenga listo?

**Comment by midudev** [comment]
Sí, por fa, crea una nueva con los pasos que me vendría genial. :) Gracias!

Cierro esta, que he cambiado la frase en la nueva versión.
