### ISSUE TITLE
Error con los emoticonos?

### ISSUE THREAD

**Issue by loadko** [midudev/libro-aprendiendo-git-issues#14]
Sección: Trabajando con Git de forma local / Deshacer el último commit / pág. 48

Es un emoticono lo que tiene que salir en la última frase o es otra cosa?

![imagen](https://user-images.githubusercontent.com/25567829/132979544-cb14110b-5c44-4a39-89fd-6d6edeff2956.png)

No es gran cosa, pero para que lo tengas en cuenta. Estoy leyendo el libro con Foxit PDF Reader pero al abrirlo en FireFox veo que tampoco sale.

**Comment by davibern** [comment]
Confirmo que en PDF tampoco sale el emoticono.

**Comment by midudev** [comment]
Arreglada en la nueva versión. :)
