### ISSUE TITLE
En la página 78 dice "Release: Cuando preparar el lanzamiento de una nueva versión.". Deberia decir "preparas"

### ISSUE THREAD

**Issue by AlexMA2** [midudev/libro-aprendiendo-git-issues#15]
Exactamente en esta zona:
• Feature: Cuando trabajas en una nueva característica para el proyecto.
• Release: Cuando **preparar** el lanzamiento de una nueva versión.
• Hotfix: Para trabajar en cambios imprevistos como parches para arreglar un
bug o un problema en producción.

Creo yo, que se quizo escribir 'preparas'.

**Comment by midudev** [comment]
Gracias Alex!
