### ISSUE TITLE
Contenito terminado y en progreso. (Una idea más que un issue)

### ISSUE THREAD

**Issue by chekobil** [midudev/libro-aprendiendo-git-issues#16]
Hola, 
veo complicado saber qué secciones del libro recibirán más contenido y cuáles no, está claro cuando lo dice explicitamente, pero si descargo una nueva versión del libro tendré que buscar donde hay cambios y donde no.
Creo que el índice sería buen lugar para indicar esto, me imagino algo así, y creo que a tí mismo te serviría para ver el estado de las secciones de un vistazo. Y cuando el libro esté terminado, el indice se limpia, de momento, también sirve para que que se entienda que está en proceso ...

> [ ] seccion por escribir, está vacía
> [+] sección a medio hacer, falta completarla
> [x] sección terminada, no recibirá más cambios

> **Hooks de Git**
        [+]¿Qué es un hook?
	[x]¿Qué hooks hay disponibles?
	[x]¿Cómo puedo crear mi propio hook?
**Alias en Git**
	[x]¿Cómo crear mi propio alias enGit?
	[x]¿Puedo crear alias para comandos que ya existen?
	[ ]¿Puedo crear un alias para un comando externo?
	[ ]¿Cómo puedo listar todos los alias que he creado?
	[ ]¿Cuáles son los mejores alias?

**Comment by midudev** [comment]
¡Hola!

En las próxima versión podréis encontrar un changelog que estará al inicio del libro para poder ver qué nuevas cosas se han añadido entre versiones. :)

**Comment by midudev** [comment]
En la nueva versión verás un Changelog al principio del libro con todos los cambios. :)
