### ISSUE TITLE
Falta de consistencia git switch

### ISSUE THREAD

**Issue by carlosala** [midudev/libro-aprendiendo-git-issues#17]
Buenas Miguel Ángel!

He estado leyendo tu libro y me parece que hay una cosa que se podría mejorar. En la página 81 del último release aparece un `git switch -C` para crear una nueva rama y después, en la 88, aparece un `git switch -c`. Creo que la forma correcta de hacerlo sería con la `-c` minúscula, pues `-C` mayúscula eliminaría cualquier rama que hubiese con ese nombre, al ser un alias de `--force-create` y podrían perderse datos de otros compañeros que hubiesen creado una rama con el mismo nombre.

Muy buen libro, lo estoy disfrutando mucho, suerte con todos los proyectos!

**Comment by midudev** [comment]
Efectivamente, se trata de un error. Debería ser con minúscula. :) Gracias por avisar Carlos!

**Comment by carlosala** [comment]
A tí! ;)
