### ISSUE TITLE
Tilde en vacio (pág 14, último párrafo)

### ISSUE THREAD

**Issue by davibern** [midudev/libro-aprendiendo-git-issues#2]
Hola Midu,

He detectado que falta la tilde en vacío, la ubicación sería:

Capítulo: un poco de teoría.
Sección: los tres estados de git.
Ubicación: después de la imagen del viaje de los ficheros, primer párrafo.

![image](https://user-images.githubusercontent.com/13550820/132260366-f9cdaacd-f9db-489e-9c36-6e54d382c4b9.png)

**Comment by BrandonDevU95** [comment]
Es correcto, hace falta el acento en la palabra vacío

**Comment by midudev** [comment]
Arreglado para la próxima versión. ✅
