### ISSUE TITLE
Error ortográfico y cambio de imagen.

### ISSUE THREAD

**Issue by Chrov** [midudev/libro-aprendiendo-git-issues#21]
Versión 2021-09-12, error ortográfico en "Un poco de Teoría, Los tres estados de GIT". Dice "Preparo los cambios los quiero grabar", sugiero cambiar el segundo "los" por un "que".

Además de esto a mi parecer la nube que se encuentra en "repositorio remoto" es poco notorio dado el fondo claro, adjunto sugerencias de nueva imagen: 
![image](https://user-images.githubusercontent.com/38703692/134282097-97012dcd-4c2a-47fc-9fb6-78e767ee015c.png)
![image](https://user-images.githubusercontent.com/38703692/134282387-51f44688-9a29-4917-b400-7126506f563a.png)

**Comment by midudev** [comment]
¡Hola Chrov! No he encontrado el texto en la última versión por lo que supongo que lo arreglé en algún momento.

Las imágenes las reharemos para sacar el libro al final cuando las tengamos todas. :) Contrataré a un dibujante para que las haga chulas.
