### ISSUE TITLE
Sugerencia para futuras versiones.

### ISSUE THREAD

**Issue by lechuss** [midudev/libro-aprendiendo-git-issues#22]
Buenas Midu.
No se si será muy complicado de hacer pero creo que  a la hora de sacar nuevas versiones sería de bastante ayuda indicar las páginas en las que has realizado los distintos cambios, sobre todo con los cambios de contenido ya que los errores ortográficos dan un poco más igual.
Creo que sería de gran ayuda para aquellas personas que llevan el libro avanzado el poder saber si hay algo distinto en las páginas anteriores.
Gracias y enhorabuena por el libro :)

**Comment by midudev** [comment]
Hola @lechuss. En las próximas versiones tendrás disponible un CHANGELOG al inicio del libro que te indica todo el contenido nuevo y revisado. :)
