### ISSUE TITLE
En iOS App Libros no funciona el modo oscuro v20-09-2021

### ISSUE THREAD

**Issue by nsdonato** [midudev/libro-aprendiendo-git-issues#27]
Antes se podía leer en modo oscuro, ahora no esta la opción para el libro, no me pasa con otros de mi biblioteca.

**Comment by midudev** [comment]
¡Hola Noelia! He probado el libro en formato EPUB en la última versión y me aparece sin problemas la posibilidad de activar el modo oscuro. Lo cierto es que es bastante raro que no te aparezca ya que por mi parte no es algo que pueda activar/desactivar. :)

**Comment by nsdonato** [comment]
Si, seguramente sea un error de la app Libros, porque yo lo uso en modo oscuro todo el tiempo, disculpa quizás no tendría que haber levantado el issue. Abrazo!

**Comment by midudev** [comment]
Para nada @nsdonato :) Te lo agradezco! Estas cosas siempre ayudan! 🤗
