### ISSUE TITLE
Sección de cambios entre versiones en índice

### ISSUE THREAD

**Issue by JordiServal** [midudev/libro-aprendiendo-git-issues#29]
En el índice general no se visualiza la sección "Cambios entre versiones del libro". 

Para aquellos que llevamos el libro al día, viene bien tener un acceso directo desde el índice sin tener que buscar dicha sección entre las páginas. Para acceder directamente a los contenidos nuevos.

Grande Midu, un saludo!

**Comment by midudev** [comment]
:) Ahora hay un changelog entre versiones!
<img width="1001" alt="CleanShot 2022-01-02 at 12 50 01@2x" src="https://user-images.githubusercontent.com/1561955/147874815-eb47daa0-faa8-457f-93e8-bddc0342ad8c.png">
