### ISSUE TITLE
Error gramatical / Página 93

### ISSUE THREAD

**Issue by Renato6GS** [midudev/libro-aprendiendo-git-issues#30]
Buenos días MIdu.

Versión 2021-11-08

He encontrado un pequeño error gramatical en la sección "Configurando la conexión SSH con GitHub" en la segunda línea.

Dice "... conectar a una servidor remoto.".
Corrección "... conectar a un servidor remoto."

![image](https://user-images.githubusercontent.com/67927947/142243414-81214dd1-c2fd-4edf-ad83-3c05fff9a530.png)

**Comment by midudev** [comment]
👏
