### ISSUE TITLE
Inconsistencia en el contenido / Página 103

### ISSUE THREAD

**Issue by Renato6GS** [midudev/libro-aprendiendo-git-issues#31]
Buenos días Midu

Versión 2021-11-08

Hay una pequeña inconsistencia en las viñetas de la sección "Flujos de trabajo y estrategias de ramas en Git" en la parte de "Git Flow" cuando explicas el tema de las dos ramas "main" y "develop". 

La inconsistencia consiste en que, en la primera viñeta de "main", terminas con dos puntos ":", mientras que cuando explicas la segunda viñeta "develop" éstos dos puntos ":" no se encuentran.

En mi opinión, creo que quedaría mejor que le coloras esos dos puntos ":" faltantes a la viñeta de "develop".

![image](https://user-images.githubusercontent.com/67927947/142248006-81074820-f9e9-418b-ac27-a4b8daae8feb.png)

Un saludo Midu 🐳

**Comment by midudev** [comment]
Gracias!
