### ISSUE TITLE
Sugerencia / Página 118

### ISSUE THREAD

**Issue by Renato6GS** [midudev/libro-aprendiendo-git-issues#32]
Hola Midu, otra vez 😂

Versión 2021-11-08

Esta vez solo vengo con una sugerencia. Se trata de la viñeta número cuatro de la página 118 en la sección de "Trunk Based Development".

Mi sugerencia es de realizar un cambio en el orden de las palabras de la segunda línea.

La oración en cuestión dice "... deshacen un pase a producción en el caso que haya algo salido mal."

Mi sugerencia sería: "... deshacen un pase a producción en el caso que algo haya salido mal."

![image](https://user-images.githubusercontent.com/67927947/142289833-cdf47ded-45f4-45ed-93ab-59c68f18c110.png)

Un saludo Midu 🦜

**Comment by midudev** [comment]
¡Me parece! Gracias!
