### ISSUE TITLE
Símbolo de más / Página 180

### ISSUE THREAD

**Issue by Renato6GS** [midudev/libro-aprendiendo-git-issues#33]
Buena tarde Midu

Versión 2021-11-08

He encontrado un símbolo de más en la sección de "¿Cómo crear tu propio alias en Git?" en el primer ejemplo.

Al final, se puede ver como una tilde o comilla simple que creo que está de más.
![image](https://user-images.githubusercontent.com/67927947/142696037-62b7b954-395f-489c-97d4-cad0753c08c5.png)

**Comment by midudev** [comment]
Gracias! 🤗
