### ISSUE TITLE
Espacio / 197

### ISSUE THREAD

**Issue by Renato6GS** [midudev/libro-aprendiendo-git-issues#34]
Buena noche Midu

Versión 2021-11-08

Hace falta un espacio en la sección de "git stash", entre las palabras "stash" y "que".

![image](https://user-images.githubusercontent.com/67927947/142959512-70e0bc51-617f-4087-87e8-b6d1d13ef267.png)

Saludos 🥶

**Comment by midudev** [comment]
Gracias Renato!
