### ISSUE TITLE
Error / Página 240

### ISSUE THREAD

**Issue by Renato6GS** [midudev/libro-aprendiendo-git-issues#35]
Buen día Midu

Versión 2021-11-08

Hay un error en la sintaxis de la tercera línea de la sección de "GitHub CLI" en el tema "Issu: Administrando Issues desde la línea de comandos". 

El error en cuestión dice "... proyectos alojados en GitHub no sólo lograr con código, si no también con la creación ..."
Mi sugerencia: "... proyectos alojados en GithHub no sólo se logra con código, si no también con la creación ..."

![image](https://user-images.githubusercontent.com/67927947/143066299-6c6a1a40-9082-4324-8e36-f83ad2825274.png)

Saludos Midu 👻

**Comment by midudev** [comment]
Gracias!
