### ISSUE TITLE
Inconsistencia en el contenido / Página 145

### ISSUE THREAD

**Issue by renansalazar** [midudev/libro-aprendiendo-git-issues#36]
Buenas noches Midu

Versión 2021-11-08

En la sección: "Buenas prácticas al trabajar con Git" en la parte de las utilidades para hacer commits al mostrar un ejemplo de husky(Página 145) esta este comentario:

_# creamos un hook para que pase los tests antes de hacer commit_

Pero deberia decir:
_# creamos un hook para que pase los tests antes de hacer push_

Porque el ejemplo muestra el uso de husky con el archivo .husky/pre-push

Excelente libro, saludos Midu!

**Comment by midudev** [comment]
¡Gracias Renan!
