### ISSUE TITLE
Versión 2021-11-08. Página 72 y siguientes. La imágenes son demasiado pequeña, apenas se ve.

### ISSUE THREAD

**Issue by mamjerez** [midudev/libro-aprendiendo-git-issues#39]

**Comment by midudev** [comment]
¡Hola Miguel Ángel! ¿Me puedes decir qué formato estás usando y en qué dispositivo lo estás viendo? Para entender mejor el problema. ¡Gracias!

**Comment by midudev** [comment]
Gracias, ya las he arreglado y espero que se vean mejor en la siguiente versión.
