### ISSUE TITLE
Imagen equivocada página 176

### ISSUE THREAD

**Issue by luciferfran** [midudev/libro-aprendiendo-git-issues#40]
Buenos días Midu!
Te cuento lo que he visto en la nueva versión lanzada 2022-01-02

En la página 176 la imágen que aparece con este texto:
"En GitHub nos mostrará información sobre si un commit ha sido firmado o no con llaves GPG y, de
esta forma, asegurarnos que la autoría es real y no simulada"

No parece corresponder con el texto ni el capítulo, además aparece en la página 195 de nuevo, donde si que parece estar bien en los Alias en Git

Un saludo

**Comment by midudev** [comment]
Gracias! Efectivamente, está mal! :)
