### ISSUE TITLE
Agregar advertencia en la sección "¿Cómo saber si tengo Git instalado en mi sistema?"

### ISSUE THREAD

**Issue by emirdaponte** [midudev/libro-aprendiendo-git-issues#41]
Version del Libro: **1.5.0**

Estaba probando los comandos de Git, y me encontre con un comando que me fallo.

```bash
$ git config --list --show-scope
```

El problema era que tenia una versión vieja de Git, y la opción `--show-scope` se agrego en la versión **2.26.0**.

Creo que estaría bueno, ademas de recomendar actualizar la version de Git como se esta haciendo, agregar una advertencia que es posible que algunos ejemplos del libro pueden fallar al utilizar un version previa a **2.33.0**

**Comment by midudev** [comment]
Genial, he añadido una pequeña advertencia justo debajo. ¡Gracias!
