### ISSUE TITLE
Errata sección git flow

### ISSUE THREAD

**Issue by maximofn** [midudev/libro-aprendiendo-git-issues#42]
Hola

En la versión del 2022-01-03, en la parte de "Ramas Release" de la sección "Git Flow" pone "Aunque no es recomendable, en las ramas release se puede seguir trabajando para añadir algún pequeño cambio de última hora o algún parche a un error que haya sido **detecto** justo antes del lanzamiento"

Creo que habría que cambiarlo por detectado

**Comment by midudev** [comment]
Buen ojo! Muchas gracias! 🙇‍♂️
