### ISSUE TITLE
Falta fusionar con rama main

### ISSUE THREAD

**Issue by maximofn** [midudev/libro-aprendiendo-git-issues#43]
Hola 

En la versión del 2022-01-03, en la parte de "Cómo crear una rama hotfix" de la sección "Git Flow" se indica crear un commit con el arreglo del problema

```
# Hacemos el commit con el arreglo del problema
$ git commit -m "Fix bug causing app not working properly"
[hotfix-2.5.1 44c2aff] Fix bug causing app not working properly
3 files changed, 24 insertions(+), 16 deletions(-)
```

Y a continuación fusionar la rama hotfix con la rama develop

```
# También fusionamos el hotfix a la rama develop
$ git switch develop
Switched to branch 'develop'
```

Creo que en medio faltaría indicar que hay que fusionar la rama hotfix con la rama main

**Comment by midudev** [comment]
¡Gracias por el aporte! 🤗
