### ISSUE TITLE
Versión 2022-01-03. Error en opción de comando git switch -b en Flujos de trabajo.

### ISSUE THREAD

**Issue by MauSousa** [midudev/libro-aprendiendo-git-issues#46]
Hola Midu, en la página 118, cuando se crea la rama hotfix se utiliza el comando git switch  -b hotfix-2.5.1 main, el problema es que git no detecta el flag -b, el comando debería ser con el flag -c para cambiar de rama.

**Comment by midudev** [comment]
Gracias! Lo he arreglado para la próxima!
