### ISSUE TITLE
Versión 2022-01-02: varias mejoras

### ISSUE THREAD

**Issue by loadko** [midudev/libro-aprendiendo-git-issues#47]
Hola,

Me faltan unas páginas para acabar el libro pero voy dejando por aquí algunas cosas.

- [x]  Falta uns `s` en `... una vez que hemos confirmado lo_s_ cambios ...`
<img width="777" alt="Captura de pantalla 2022-01-21 a las 15 48 01" src="https://user-images.githubusercontent.com/25567829/151075215-ba26d13f-93a7-44bd-b6db-0d9cc3524bbe.png">

- [x] Quitar el `más`, `... es la _más_ la más antigua ...`
<img width="777" alt="Captura de pantalla 2022-01-22 a las 23 19 29" src="https://user-images.githubusercontent.com/25567829/151075621-15d87ec0-b685-46c8-896c-91d373a0a813.png">

- [x] No acabo de entender el punto 5. No suena mejor esto? `El equipo ha sabido lidiar con el ego individual, confia en el resto del equipo, las pruebas automáticas pasan y considera que la rama princial puede no contener código perfecto siempre.`
<img width="777" alt="Captura de pantalla 2022-01-22 a las 23 28 39" src="https://user-images.githubusercontent.com/25567829/151075862-0ecd3c08-166e-4b31-beb8-ac503487056e.png">

- [x] Dejar un espacio después de `... que el comando sourcetree_ _se ejecutará ...`
<img width="777" alt="Captura de pantalla 2022-01-25 a las 23 53 50" src="https://user-images.githubusercontent.com/25567829/151074952-2cb413b2-2b3a-4bee-aab8-9c48f99dcd0a.png">

**Comment by midudev** [comment]
Genial, gracias por los aportes y aportar también la captura! :) He añadido las correcciones para la próxima versión!
