### ISSUE TITLE
GitLab escrito con "L" minúscula 

### ISSUE THREAD

**Issue by juansemprun** [midudev/libro-aprendiendo-git-issues#48]
- **Versión:**  03/01/2022
- **Capítulo:** Buenas prácticas al trabajar con Git
- **Sección:** Firma correctamente tus commit con GPG -> **_Configurando GitHub_**
- **Página:**  145

![image](https://user-images.githubusercontent.com/33623712/152420307-42955d72-170d-4c7b-9270-4bd0664699cc.png)

**Comment by midudev** [comment]
Arrelgado! Gracias!
