### ISSUE TITLE
Añadir "src/" a uno de los resultados de git blame

### ISSUE THREAD

**Issue by juansemprun** [midudev/libro-aprendiendo-git-issues#49]
- **Versión:** 03/01/2022
- **Capítulo:** Trucos con Git
- **Sección:** ¿Quién ha tocado este fichero? ¿Quién ha hecho cambios?
- **Página:** 182

![image](https://user-images.githubusercontent.com/33623712/152648601-8a7239ae-6690-4cee-8bed-63ab27c4cc62.png)

**Comment by midudev** [comment]
✅ Gracias!
