### ISSUE TITLE
Palabra extra o fuera de lugar

### ISSUE THREAD

**Issue by JuaniSilva** [midudev/libro-aprendiendo-git-issues#50]
Hola! En la versión del libro publicada el 2022-01-03 en el capitulo de "Flujos de trabajo y estrategias de ramas en Git" en la sección "Trunk Based Development" en la página 125 en el recuadro dice "Por raro que parezca, esta estrategia es **más** la más antigua de todas las que hemos visto." 
Creo que la oración estaba intencionada a que diga "Por **más** raro que parezca, esta estrategia es la más antigua de todas las que hemos visto."

**Comment by midudev** [comment]
Muchas gracias Juani! :) Lo he arreglado para la próxima versión!
