### ISSUE TITLE
git add . O git commit -am de mas

### ISSUE THREAD

**Issue by jonathino2590** [midudev/libro-aprendiendo-git-issues#52]
En la versión del 2022-01-03,en la página 81 creo que está de más añadir el git add . , cuando en la siguiente linea colocas un git commit -am

Podrías dejar uno de los dos para no confundir a las personas que recién empiezan.

![image](https://user-images.githubusercontent.com/5762081/159147030-06ba4332-7b7f-4136-ba6c-98b6f09713bc.jpeg)

**Comment by midudev** [comment]
Buenísimo, gracias!
