### ISSUE TITLE
Sugerencía en consistencía de comandos - Versión 2022-01-03

### ISSUE THREAD

**Issue by alejss** [midudev/libro-aprendiendo-git-issues#53]
Sugerencía en ejemplo de "$ git commit -a -m Bump version to 2.5.1"  cambiarlo por "$ git commit -am "Bump version to 2.5.1" para mantener constancía de comandos a usar ya que los ejemplos anteriores se usa siempre "-am".

Página 118

**Comment by midudev** [comment]
¡Perfecto! 👍
