### ISSUE TITLE
Error ortográfico pág. #172

### ISSUE THREAD

**Issue by jonathino2590** [midudev/libro-aprendiendo-git-issues#54]
En la versión del 03-01-2022 se tiene un error de ortografía en la página 172

La palabra que indica es anteriromente cuando debería ser anteriormente. 

![image](https://user-images.githubusercontent.com/5762081/160318488-edf01b18-6a1f-422f-b5f7-f3fcd9a2ac32.jpeg)

**Comment by midudev** [comment]
Arreglado para la próxima versión. ¡Gracias!
