### ISSUE TITLE
Error en el nombre de la rama al crearla con stash

### ISSUE THREAD

**Issue by jonathino2590** [midudev/libro-aprendiendo-git-issues#55]
En la versión del 03-01-2022 en la página #220,al momento que se crea una rama nueva a partir de un índice de stash, estás creando la rama con el nombre optimize-css pero el output del comando está mostrando que la creas con el nombre css 

![image](https://user-images.githubusercontent.com/5762081/160323571-3ffd9a00-fd3e-465d-af44-d6ebdab9e092.jpeg)

**Comment by midudev** [comment]
Arreglado para la próxima versión. ¡Gracias!

**Comment by jlopez-technisys** [comment]
@midudev veo que en la version del 24/04/2022 aun continua la novedad.
