### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by nob322** [midudev/libro-aprendiendo-git-issues#56]
dónde se puede leer el libro para colaborar con el mismo?

**Comment by jonathino2590** [comment]
Debes comprarlo https://leanpub.com/aprendiendo-git

**Comment by nob322** [comment]
ahora voy corriendo, esperame.
________________________________
De: Jonathan Lopez Torres ***@***.***>
Enviado: jueves, 19 de mayo de 2022 23:50
Para: midudev/libro-aprendiendo-git-issues ***@***.***>
Cc: David ***@***.***>; Author ***@***.***>
Asunto: Re: [midudev/libro-aprendiendo-git-issues] Dudas (Issue #56)


Debes comprarlo https://leanpub.com/aprendiendo-git

**Comment by midudev** [comment]
Gracias @jonathino2590!
