### ISSUE TITLE
Posible error gramatical / página 6

### ISSUE THREAD

**Issue by avelezdo** [midudev/libro-aprendiendo-git-issues#58]
Versión de la edición: 2022-04-24

En la sección "Requisitos previos", la frase "Esto quiere decir que en Windows debería estar usando la
consola Bash de Ubuntu..." la palabra "debería" debería ser, a mi modo de ver, "deberías". Creo que así tendría más sentido.

**Comment by midudev** [comment]
Arreglado para la próxima versión.
