### ISSUE TITLE
Faltas de ortografia

### ISSUE THREAD

**Issue by FJFrau** [midudev/libro-aprendiendo-git-issues#60]
Apartado del libro: Ramas en Git
Página de libro: 78
----------------------------------------------------------------

Buenas Midu! Reportar una falta menor que me he encontrado hoy mientras leia y estudiaba tu libro :). Este es el párrafo:

<code>
si estamos actualmente en la rama
main y hacemos un git merge my-branch haremos que la rama main **_incorporé_** y
fusione los cambios que había en la rama my-branch
</code>
<br>
<br>

Simplemente es quitar el acento en "incorporé" para que vaya acorde al resto de la frase.
No he visto una issue general de incidencias de ortografia/gramática, y no se si es necesario crearlo. En cualquier caso queda reportado :)

**Comment by FJFrau** [comment]
Apartado del libro: Trabajando con Git de forma remota
Pagina del libro: 96
-------------------------

Buenas!

Como he detectado otro fallo de este tipo he modificado el título de la issue y voy a añadir aquí un nuevo comentario con el fallo en cuestión. frase:

<code>
No es muy usado pero a veces queremos trabajar
con el mismo **_repositorios_** en dos directorios de trabajo y hacerlo puede ayudarte
</code>
<br>
<br>

Cambiarlo por "repositorio".
Un saludo!

**Comment by matiashernandev** [comment]
> ## Apartado del libro: Ramas en Git
> Página de libro: 78
> 
> Buenas Midu! Reportar una falta menor que me he encontrado hoy mientras leia y estudiaba tu libro :). Este es el párrafo:
> ` si estamos actualmente en la rama main y hacemos un git merge my-branch haremos que la rama main **_incorporé_** y fusione los cambios que había en la rama my-branch `
> 
> Simplemente es quitar el acento en "incorporé" para que vaya acorde al resto de la frase. No he visto una issue general de incidencias de ortografia/gramática, y no se si es necesario crearlo. En cualquier caso queda reportado :)

Agrego una captura con la que iba a comentar lo mismo.  Esta  versión se  publicó  en  2022-04-24
![midutilde](https://user-images.githubusercontent.com/73903008/199760505-2004407d-d355-4b19-9fa5-b4debc428888.jpg)

**Comment by midudev** [comment]
Arreglado, gracias a ambos!
