### ISSUE TITLE
Correción en imagen

### ISSUE THREAD

**Issue by moslisnas** [midudev/libro-aprendiendo-git-issues#61]
Hola, reporto un pequeño "error" tras la lectura.

Edición: 2022-04-24
Apartado: Ramas - Fusionando ramas - _git merge_ el comando para fusionar ramas, en la página 79.

En el lateral izquierdo de la imagen se aprecia un borde que queda un poco raro, creo que quedaría mejor la imagen si no se viese:
![image](https://user-images.githubusercontent.com/7356108/188288903-b0719450-bad2-4e18-a7ed-6fc6630df700.png)

**Comment by midudev** [comment]
Hecho!
