### ISSUE TITLE
Falta un carácter en "gist"

### ISSUE THREAD

**Issue by moslisnas** [midudev/libro-aprendiendo-git-issues#62]
Hola, he detectado que falta un carácter "s" en la palabra gist.

Edición: 2022-04-24
Apartado: GitHub CLI - _gist_: Administrando gists desde la línea de comandos - Más comandos para administrar _gists_, en la página 305.

Así está:
![image](https://user-images.githubusercontent.com/7356108/188291776-3c047a0f-0ce5-4c12-9c58-a188dfcfc360.png)

Con la corrección:
Una vez hemos creado nuestro **gist**, ...

**Comment by midudev** [comment]
Gracias!
