### ISSUE TITLE
Error de consistencia en ejecución de comandos

### ISSUE THREAD

**Issue by moslisnas** [midudev/libro-aprendiendo-git-issues#63]
Hola, he detectado una pequeña inconsistencia en un conjunto de ejecuciones.

Edición: 2022-04-24
Apartado: Trucos con Git - Vuelve a la rama previa en la que estaba trabajando, en la página 262.

La inconsistencia se produce ya que en un paso se muestra que la rama es _main_ y posteriormente, al utilizar el comando de volver a la rama anterior _git switch -_, aparece la rama _master_

Así está:
![image](https://user-images.githubusercontent.com/7356108/188290882-b3fee796-10b6-4c8d-a9e5-a3b8650eb370.png)

Cómo considero que debería quedar:
_#¡quiero volver a la rama anterior!
$ git switch -
Switched to branch '**main**'
Your branch is up to date with 'origin/**main**'._

**Comment by midudev** [comment]
Arreglado!
