### ISSUE TITLE
Correción semántica título

### ISSUE THREAD

**Issue by moslisnas** [midudev/libro-aprendiendo-git-issues#64]
Hola, he detectado un título que queda un poco extraño bajo mi punto de vista.

Edición: 2022-04-24
Apartado: Errores comunes en Git y sus soluciones, en la página 280.

Así está:
![image](https://user-images.githubusercontent.com/7356108/188291715-0b22cd8b-2243-492a-91a2-b12040ec5b59.png)

Como creo que quedaría mejor:
He hecho commits a la rama principal **que debían realizarse en otra rama**

**Comment by midudev** [comment]
Arreglado!
