### ISSUE TITLE
Correccion del primer parrafo de la pagina 14 (¿Qué es Git?)

### ISSUE THREAD

**Issue by coriglianogiulianijuanmanuel** [midudev/libro-aprendiendo-git-issues#65]
Buenas! Queria aportar mi correccion de algo que acabo de leer, y que como usuario de GNU/Linux creo que esta mal redactado:

En el primer parrafo de la pagina 14 (¿Qué es Git?) dice: 

`Git es un un sistema distribuido de control de versiones, gratuito y de código abierto bajo licencia GPLv2. Fue diseñado originalmente por Linus Torvalds, el creador de Linux.`

El problema con este parrafo es que Linus Torvalds no es "el creador de Linux", es el creador del "kernel Linux" y titular de la marca "Linux". En conjunto con GNU crearon dicho SO. La intencion de esta correccion es para evitar cualquier posible malentendido futuro dada la constante discusion que se da entre GNU y Linux por la adjudicacion/credito de la creacion del sistema operativo.

**Comment by midudev** [comment]
Visto, gracias por la aclaración!
