### ISSUE TITLE
Git restore (pág 34)

### ISSUE THREAD

**Issue by davibern** [midudev/libro-aprendiendo-git-issues#7]
Hola Midu,

Esto es una sugerencia, se ha comentado en el canal del libro de discord.

Capítulo: Trabajando con Git de forma local
Artículo: ¿Cómo deshacer un archivo modificado? Si has modificado un archivo o directorio que ya existía.

Lo que me ha pasado es que he seguido los comandos indicados en el libro y cuando he ido a ejecutar el **git restore** me he encontrado con lo siguiente:

```
PS D:\Desarrollo\Git-Curso> git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        index.html
        test.html

nothing added to commit but untracked files present (use "git add" to track)
PS D:\Desarrollo\Git-Curso> git restore index.html
error: pathspec 'index.html' did not match any file(s) known to git
PS D:\Desarrollo\Git-Curso> git checkout -- index.html
error: pathspec 'index.html' did not match any file(s) known to git
```

Luego se comenta más adelante que el archivo tiene que estar aceptado (commit) para poder usar el restore, pero no se indica antes, y me he llevado un rato buscando el error.

Sólo es una sugerencia, pues lo que me ha ocurrido a mi es posible que le pase a más gente, y mi propuesta es que se indique antes de usar dicho comando en la página 35 que hay que usar previamente el commit para restaurar.

O no sé si estoy realmente entendiendo bien el propósito de dicho comando, pero bueno, lo dejo como sugerencia.

PD: me está encantando el libro!!! 👍

**Comment by midudev** [comment]
Hola @davibern,

en el título de la sección que comentas pone: "Si has modificado un archivo o directorio que ya existía". 

Voy a añadir igualmente un párrafo para que quede más claro.

**Comment by davibern** [comment]
¡Muchas gracias por el trabajazo con el libro!
