### ISSUE TITLE
Falta una letra en página 215

### ISSUE THREAD

**Issue by cipriansauliuc** [midudev/libro-aprendiendo-git-issues#72]
_Estas variables_ en vez de _Esta variable_:

'Esta variables ahora las podemos interpolar en el string de forma que hacemos que los mensajes sean de un color.'

**Comment by cipriansauliuc** [comment]
También, como sugerencia, creo que se puede mejorar un poco esta frase y que de paso no tenga tantos _que_, por ejemplo:

Estas variables, ahora se pueden interpolar en el string de forma que hagamos los mensajes de un solo color.
Estas variables, ahora se pueden interpolar en el string para hacer que los mensajes sean de un solo color.

**Comment by midudev** [comment]
Hecho!
