### ISSUE TITLE
Error de ortografía en página 221

### ISSUE THREAD

**Issue by cipriansauliuc** [midudev/libro-aprendiendo-git-issues#73]
La siguiente frase no es correcta:
'En el caso que un alias tenga el nombre de un comando de git ya definido, se ignorará el alias (no recibirás un error al crearlo).'

Tal y como se explica en el Diccionario panhispánico de dudas, para no caer en el queísmo, las expresiones _en caso de que_ y _en el caso de que_ se construyen con la preposición _de_, por lo que no son válidas las formas _en caso que_ ni _en el caso que_. [Fuente](https://www.fundeu.es/recomendacion/en-caso-de-que-o-en-el-caso-de-que-no-en-caso-que/)

Solución:
'En el caso de que un alias tenga el nombre de un comando de git ya definido, se ignorará el alias (no recibirás un error al crearlo).'

**Comment by midudev** [comment]
Gracias crack!
