### ISSUE TITLE
Falta tilde en página 296

### ISSUE THREAD

**Issue by cipriansauliuc** [midudev/libro-aprendiendo-git-issues#77]
En la siguiente frase, _mí_ debe llevar tilde:
'# En este caso me la asigno a mi mismo y quito a...'

**Comment by cipriansauliuc** [comment]
Mismo error en la página 298 (hay dos errores en esta página):
'# muestra las issues asignadas a mi'
'# las issues que ya han sido cerradas asignadas a mi'

**Comment by midudev** [comment]
Gracias!
