### ISSUE TITLE
Versión 2022-04-22 Pág. 17 "Al usar Git, los archivos de tu proyecto se puede encontrar..."

### ISSUE THREAD

**Issue by palcaraz** [midudev/libro-aprendiendo-git-issues#81]
Donde dice "Al usar Git, los archivos de tu proyecto se puede encontrar" 
debería decir
"Al usar Git, los archivos de tu proyecto se pueden encontrar"

Saludos

**Comment by midudev** [comment]
Arreglado, gracias!
