### ISSUE TITLE
[v. 2022-04-24] Redacción extraña y una tilde de más en el primer párrafo (página 115)

### ISSUE THREAD

**Issue by emigimenezj** [midudev/libro-aprendiendo-git-issues#86]
¡Buenas! ¿Qué tal?

Aporto una revisión más sobre una falta ortográfica y una redacción que creo que queda algo extraña.

Sección: **¿Por qué debería contribuir al código abierto?** (al inicio)
«Podría intentar convencerte `qué` tienes una deuda con el código abierto ya que, [...]»
Este `qué` no lleva tilde ya que no tiene sentido interrogativo o exclamativo directo o indirecto. [ref. rae](https://www.rae.es/espanol-al-dia/tilde-en-que-cuales-quienes-como-cuan-cuantoaosas-cuando-donde-y-adonde)
Además, personalmente creo que la redacción sería: «Podría intentar convencerte `de que` tienes una deuda [...]» _(agregando el `de`)_

En el siguiente párrafo, sucede algo parecido con la redacción.
«En lugar de eso, quiero convencerte `que` contribuir de alguna forma [...]»
En vez de: «En lugar de eso, quiero convencerte `de que` contribuir de alguna forma [...]»

❤️

**Comment by midudev** [comment]
Arreglado. Gracias!
