### ISSUE TITLE
Enlace roto hacia artículo de referencia

### ISSUE THREAD

**Issue by dfragar** [midudev/libro-aprendiendo-git-issues#87]
Hola @midudev, te dejo a continuación el siguiente error detectado:

**Edición del libro:** 24/04/2022
**Capítulo:**  Un poco de teoría
**Sección:**  ¿Qué es Git?
**Página:** 13

En dicha página, la referencia de anotación 12 situada en el pie, aparece un enlace hacia una web en la que se muestra un artículo de la entrevista realizada a Linus Torvalds con motivo de la celebración de los 10 años de Git ([enlace aquí](https://www.linuxfoundation.org/blog-new/blog/10-years-of-git-an-interview-with-git-creator-linus-torvalds#:~:text=Why%20did%20you%20create%20Git,all%20SCM's%20with%20a%20passion.)). Al hacer clic en dicho enlace te lleva a la web de linuxfoundation mostrando el error "404 Page Not Found".

**Solución:** 
Actualmente dicho artículo ha sido removido al siguiente enlace: https://www.linuxfoundation.org/blog/blog/10-years-of-git-an-interview-with-git-creator-linus-torvalds

**Comment by midudev** [comment]
Arreglado, gracias!
