### ISSUE TITLE
[v. 2023-01-03 ] - Error de redacción - Página 83

### ISSUE THREAD

**Issue by NahuelOrselli** [midudev/libro-aprendiendo-git-issues#88]
... Git crea un commit automáticamente y lo **grabado**. 

No se si sería " y lo graba" o " y lo guarda"

<img width="712" alt="Captura de pantalla 2023-02-27 a la(s) 11 19 52" src="https://user-images.githubusercontent.com/103908691/221588995-bffdae89-eafe-464e-9c5d-ebc83994ee6b.png">

**Comment by midudev** [comment]
Arreglado, gracias!
