### ISSUE TITLE
[v. 2023-01-03 ] - Error de redacción - Página 85

### ISSUE THREAD

**Issue by NahuelOrselli** [midudev/libro-aprendiendo-git-issues#89]
Quedó fuera del comentario las letras "tml", solo habría que  ponerla dentro para que quede "... index.html \"

<img width="696" alt="Captura de pantalla 2023-02-27 a la(s) 11 39 12" src="https://user-images.githubusercontent.com/103908691/221593339-cb6dced9-b9a6-40ce-a322-6287d2e4afe9.png">

**Comment by midudev** [comment]
Arreglado, gracias!
