### ISSUE TITLE
[v. 2023-01-03 ] - Estilos de títulos y Error de redacción - Página 149

### ISSUE THREAD

**Issue by guzmanpdro** [midudev/libro-aprendiendo-git-issues#90]
El segundo y tercer punto no están en negrita

**Solución:**
- **Ahora el repositorio te pertenece.**
- **Un mensaje pequeñito nos indica que este repositorio es un fork de otro.**
- **Un mensaje nos indica que la rama en la que nos encontramos está sincronizada con la misma rama del repositorio original.**

En la frase final del primer punto se coló un "de" entre las palabras estos y permisos

**Solución:** 

- Significa que con estos permisos de administración puedes hacer lo que quieras con este repositorio.

![image](https://user-images.githubusercontent.com/47934050/226516036-77d746fc-e83b-4f51-90a7-61b5b238bb4f.png)

**Comment by midudev** [comment]
Arreglado, gracias!
