### ISSUE TITLE
Error de typo

### ISSUE THREAD

**Issue by JimenezR** [midudev/libro-aprendiendo-git-issues#92]
Antes que nada excelente libro, un gran aporte a la comunidad

tienes un ligero error, en la sección de 

### 1.7.0 (diciembre 2022)
- “Arreglados más de 50 typos gracias `al a` comunidad.”

debe ser `a la`

<img width="1800" alt="image" src="https://github.com/midudev/libro-aprendiendo-git-issues/assets/19743250/9c922f9a-3ab7-4476-8330-553d3396ba8b">

Saludos!

**Comment by midudev** [comment]
Gracias!
