### ISSUE TITLE
Error en página 18

### ISSUE THREAD

**Issue by beenjii14** [midudev/libro-aprendiendo-git-issues#93]
Hay un typo en la página 18 en la sección de: **Cambios entre versiones del
libro** porque dice: _Arreglados más de 50 typos gracias al a comunidad._ y lo correcto seria: _Arreglados más de 50 typos gracias **a  la** comunidad._

<img width="691" alt="error" src="https://github.com/midudev/libro-aprendiendo-git-issues/assets/22719098/6630018a-05c2-44e4-acf2-a4c729337ffd">

**Comment by midudev** [comment]
Arreglado en la última versión.
