### ISSUE TITLE
Error de nombre de ramas en la sección "Vuelve a la rama previa en la que estaba trabajando"

### ISSUE THREAD

**Issue by cristian-corbalan** [midudev/libro-aprendiendo-git-issues#94]
En dicha sección se muestra los comandos para volver a la rama anterior a la que estamos actualmente, los cuales son los siguientes:

![image](https://github.com/midudev/libro-aprendiendo-git-issues/assets/73001243/9d3c28c8-a825-45c0-9beb-430932e6a956)

El problema está en que en lugar de mostrar la rama "main", muestra dice "master".

**Comment by midudev** [comment]
Arreglado en la última versión!
